<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'suquisa');
define('_DB_USER_', 'root');
define('_DB_PASSWD_', 'xm8AB24wBEreteTN');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', '8ZmQBK0xqrkxQM2dhVAFKCfxnTozciKBxiByFPbr6UdB1YnonX1r1nag');
define('_COOKIE_IV_', 'anOuKUru');
define('_PS_CREATION_DATE_', '2014-09-03');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', 'j6Xc2g4HpyJGhvHf1UeyUMEqGesUZvPT');
define('_RIJNDAEL_IV_', 'ABN1M5wh6QWLoKWLlnkxcA==');
